import RootLayout from './../app/layout';
import { QueryClientProvider, QueryClient } from 'react-query';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'E-commerce Site',
  description: 'Generated by create next app',
};

function MyApp({ Component, pageProps: { session, ...pageProps } }) {
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <RootLayout>
        <ToastContainer />
        <Component {...pageProps} />
      </RootLayout>
    </QueryClientProvider>
  );
}

export default MyApp;
