import RootLayout from "./../app/layout";
import { QueryClientProvider, QueryClient } from "react-query";

export const metadata = {
  title: "E-commerce Site",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }) {
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <RootLayout>
        <Component {...pageProps} />
      </RootLayout>
    </QueryClientProvider>
  );
}

export default MyApp;
