import RootLayout from './../app/layout';
import { QueryClientProvider, QueryClient } from 'react-query';
import { SessionProvider } from 'next-auth/react';

export const metadata = {
  title: 'E-commerce Site',
  description: 'Generated by create next app',
};

function MyApp({ Component, pageProps: { session, ...pageProps }}) {
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <SessionProvider session={session}>
        <RootLayout>
          <Component {...pageProps} />
        </RootLayout>
      </SessionProvider>
    </QueryClientProvider>
  );
}

export default MyApp;
